**2. Variables**

2.1. Initializing a variable and output it

In [24]:
x <-7
y="hey"
print(x)
y

[1] 7


[1] "hey"

2.2. Overwriting

In [27]:
w<-7
w<-99
w

[1] 7

2.3. Single and double quotes

In [33]:
j="yes"
k='yes'
j
k # exception escape characters

[1] "yes"

[1] "yes"

2.4. Variable Names

In [35]:
hey=88 # one word
jojo8z=77 # numbers
jojo_r=99 # underscore
Jojo=55 # uppercase
.jojo=9 # start with period

2.5. Assign same value to multiple variables

In [39]:
x=y=z=222
y

[1] 222

(2.6. Concatenation)

In [2]:
x<-"hey"
y<-"yo"
paste(x, y)
paste("hey", y)
z<-7
z + z
5+99

[1] "hey yo"

[1] "hey yo"

[1] 14

[1] 104

**3. Comment**

In [40]:
# this is a comment

In [1]:
a="hey"
class(a)

[1] "character"

**4. Operators**

**5. Integer data type**

In [5]:
x <-5L

[1] "integer"

5.1. Convert to numeric or complex

In [9]:
num<-as.numeric(x)
com<-as.complex(x)

[1] 5

**6. Numeric data type**

In [10]:
y<-8.8
z<-9

6.1. Convert to integer or complex

In [18]:
int<-as.integer(y)
comp<-as.complex(y)

**7. Complex data type**

In [21]:
a<-7i
b<-99.7+3i
# no conversion possible

**8. String data type**

In [ ]:
str1<-"hey"
str2<-'hey'

8.1. Multiline Strings

In [24]:
str <- "Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua." # will insert line breaks
str
# print normal without escape characters
cat(str)

[1] "Lorem ipsum dolor sit amet,\nconsectetur adipiscing elit,\nsed do eiusmod tempor incididunt\nut labore et dolore magna aliqua."

Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.

8.2. String length

In [25]:
nchar(str)

[1] 123

8.3. Check if value is present

In [29]:
grepl("ipsum", str)


# concatenation need paste function

[1] TRUE

8.4. Escape characters

In [33]:
# 1 Single Quote
print('This is an example of a single quote: \'')

# 2 Double Quote
print("This is an example of a double quote: \"")

# 3 Backslash
print("This is an example of a backslash: \\")

# 4 New Line
print("This is an example of a new line:\nSecond line")

# 5 Tab
f<-("This is an example of a tab:\tSecond column")

f
cat(f)

[1] "This is an example of a single quote: '"
[1] "This is an example of a double quote: \""
[1] "This is an example of a backslash: \\"
[1] "This is an example of a new line:\nSecond line"


[1] "This is an example of a tab:\tSecond column"

This is an example of a tab:	Second column

**9. Boolean data type**

In [35]:
# Compare values
9 == 100
3<9
# if statements (later)

[1] FALSE

[1] TRUE

**10. Operators**

10.1. Arithmetic operators

In [37]:
#1 Exponent
8^4

#2 Modulus
8 %% 4
#3 Integer Division
8 %/%4

#4 Division
8/4

#5 Multiplication
8*4

#6 Subtraction
8-4

#7 Addition
8+4

[1] 4096

[1] 0

[1] 2

[1] 2

[1] 32

[1] 4

[1] 12

10.2. Assignement operators

In [ ]:
my_var <- 3

my_var <<- 3

3 -> my_var

3 ->> my_var

10.3. Comparison operators

In [39]:
#1 equal to
print(6==7)

#2 not equal to
print(6!=7)

#3 less than
print(7<6)

#4 greater than
print(7>6)

#5 less than or equal to
print(7<=7)

#6 greater than or equal to
print(7>=6)


# Special Cases
print(1==TRUE)
print(0==TRUE)
print(0==FALSE)

[1] FALSE
[1] TRUE
[1] FALSE
[1] TRUE
[1] TRUE
[1] TRUE
[1] TRUE
[1] FALSE
[1] TRUE


10.4. ...???

In [6]:
word<-c("red", "green", "blue")
for (x in word) {
    print(x)
}

[1] "red"
[1] "green"
[1] "blue"


**xy. Built-in functions**

In [34]:
# paste, print, class, as.integer * 3, abs, sqrt, min, max, ceiling, floor, cat, length, sort

**xz. User-defined functions**

**Vectors**

Initializing vectors

In [12]:
a<-c(3, 5, 6, 8)
b<-1:10.8
c<-c("a", "b", "c")
d<-seq(from=0, to=20, by=2)

Indexing and Slicing

In [18]:
c[1] # index starts at 1
a[c(1, 4)] # access multiple items
a[-2] # show every item except the specified one
a[3]<-9 # change item

[1] "a"

[1] 3 8

[1] 3 6 8

Repeat vectors

In [26]:
repeat_each <- rep(c(1,2,3), each = 3) 
repeat_times <- rep(c(1,2,3), times = 3)
repeat_indepent <- rep(c(1,2,3), times = c(5,2,1))
repeat_each
repeat_times
repeat_indepent


# length and sort

[1] 1 1 1 2 2 2 3 3 3

[1] 1 2 3 1 2 3 1 2 3

[1] 1 1 1 1 1 2 2 3

**Lists**

In [37]:
mylist<-list("a", 1, "b", 2)

Indexing and slicing

In [38]:
mylist[1]
mylist[2]<-5.1
mylist
(mylist)[2:4] # last item included

[[1]]
[1] "a"

[[1]]
[1] "a"

[[2]]
[1] 5.1

[[3]]
[1] "b"

[[4]]
[1] 2

[[1]]
[1] 5.1

[[2]]
[1] "b"

[[3]]
[1] 2

Operator ???

In [39]:
2 %in% mylist

[1] TRUE

In [40]:
length(mylist)
append(mylist, 55)
append(mylist, "ok", after=2)
# remove
mylist
mylist<-mylist[-2]

[1] 4

[[1]]
[1] "a"

[[2]]
[1] 5.1

[[3]]
[1] "b"

[[4]]
[1] 2

[[5]]
[1] 55

[[1]]
[1] "a"

[[2]]
[1] 5.1

[[3]]
[1] "ok"

[[4]]
[1] "b"

[[5]]
[1] 2

[[1]]
[1] "a"

[[2]]
[1] 5.1

[[3]]
[1] "b"

[[4]]
[1] 2

In [41]:
for (x in mylist) {
    print(x)
}

[1] "a"
[1] "b"
[1] 2


In [42]:
list<-list("yes", "no", 8)
new<-c(mylist, list)
new

[[1]]
[1] "a"

[[2]]
[1] "b"

[[3]]
[1] 2

[[4]]
[1] "yes"

[[5]]
[1] "no"

[[6]]
[1] 8

**Matrices**

In [49]:
thismatrix <- matrix(c(1,2,3,4,5,6), nrow = 3, ncol = 2)

Indexing and Slicing

In [50]:
thismatrix[2, 2] # row, column
thismatrix[2,] # whole row
thismatrix[,2] # whole column
thismatrix[c(1,2),] # more than one row
thismatrix[,c(1,2)] # more than one column

[1] 5

[1] 2 5

[1] 4 5 6

[,1] [,2]
[1,] 1    4   
[2,] 2    5

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

**Arrays**

In [45]:
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2)) # rows, columns, dimensions
thisarray
multiarray

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

[1] 18

Indexing and Slicing

In [ ]:
multiarray[2, 2, 2]  # row, column, matrix level
multiarray[,c(1), 1]
multiarray[c(1),,1]

Operator

In [46]:
4 %in% multiarray

[1] TRUE

In [47]:
dim(multiarray)
# length

[1] 4 3 2

In [48]:
for (x in multiarray){
    print(x)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20
[1] 21
[1] 22
[1] 23
[1] 24
